Repository Calindra/nonodo, pull requests merged in 2024-10, with the labels that each got.

#233 Decode ABI -> EIP712
  internal/contracts/eip712.go
  internal/contracts/generate/main.go
  internal/paio/paio.go
  internal/paio/paio.json
  internal/paio/paio_test.go
Labels: avail

#229 Remove fields
  api/reader.graphql
  internal/reader/graph/generated.go
  internal/reader/reader.resolvers.go
  loadtesting/test.js
Labels: espresso

#198 feat: bump version
  internal/contracts/generate/main.go
Labels: enhancement

#243 Bugfix/output index
  api/reader.graphql
  internal/convenience/container.go
  internal/convenience/decoder/decoder_test.go
  internal/convenience/repository/notice_repository.go
  internal/convenience/repository/output_repository.go
  internal/convenience/repository/report_repository.go
  internal/convenience/repository/report_repository_test.go
  internal/convenience/repository/voucher_repository.go
  internal/convenience/repository/voucher_repository_test.go
  internal/convenience/services/service.go
  internal/convenience/services/service_test.go
  internal/convenience/synchronizer/graphile_fetcher_test.go
  internal/model/model_test.go
  internal/model/state.go
  internal/nonodo/nonodo.go
  internal/reader/adapter.go
  internal/reader/adapter_test.go
  internal/reader/adapter_v1.go
  internal/reader/adapter_v2.go
  internal/reader/adapter_v2_test.go
  internal/reader/graph/generated.go
  internal/reader/reader.resolvers.go
  internal/rollup/rollup_test.go
  internal/sequencers/espresso/espresso_client_test.go
  main.go
Labels: bug

#238 Add diagram to documentation
  docs/espresso.md
Labels: documentation, espresso

#242 Add Paio Decoder on demand
  DEV2DEV.md
  internal/commons/eip712.go
  internal/commons/handle_release.go
  internal/devnet/anvil.go
  internal/nonodo/nonodo.go
  internal/paio/paio.go
  internal/paio/paio_sender.go
  internal/paio/paio_sender_test.go
  internal/paio/sender.go
  internal/sequencers/avail/avail_listener.go
  internal/sequencers/avail/avail_listener_test.go
  internal/sequencers/inputter/inputter_test.go
  internal/sequencers/paiodecoder/decode_batch.go
  internal/sequencers/paiodecoder/parser.go
  internal/sequencers/paiodecoder/parser_test.go
  internal/supervisor/server.go
  main.go
  paio-bin/decode-batch
Labels: avail

#245 Add badge release for v1
  README.md
Labels: documentation
