Repository Calindra/nonodo, pull requests merged in 2024-09, with the labels that each got.

#193 feat: add support to riscv
  .github/workflows/ci.yaml
Labels: enhancement

#194 Add Riscv to V1
  .github/workflows/ci.yaml
Labels: enhancement

#195 Add timeout flag for worker
  internal/nonodo/nonodo.go
  internal/supervisor/supervisor.go
  main.go
Labels: enhancement

#187 Pin version openapi to 0.9.0 instead permalink and bump sdk/cli
  api/generate/main.go
  internal/devnet/gen-devnet-state/main.go
Labels: enhancement

#199 adding espresso send command
  api/reader.graphql
  go.mod
  go.sum
  internal/nonodo/nonodo.go
  internal/reader/graph/generated.go
  internal/reader/model/generated.go
  internal/sequencers/espresso/espresso_client.go
  main.go
Labels: enhancement, espresso

#205 Update Anvil version and fix installation
  .env
  .github/workflows/ci.yaml
  .gitignore
  Dockerfile
  docker-compose.yml
  go.mod
  go.sum
  internal/commons/utils.go
  internal/devnet/anvil.go
  main.go
  sqlite3
Labels: bug

#206 Pin Anvil state
  .env
  .github/workflows/ci.yaml
  .gitignore
  Dockerfile.dev
  go.mod
  go.sum
  internal/commons/handle_release.go
  internal/commons/utils.go
  internal/devnet/anvil.go
  main.go
Labels: bug

#213 Subscribe to avail with cartesi namespace
  .vscode/settings.json
  DEV2DEV.md
  README.md
  docs/avail.md
  go.mod
  go.sum
  internal/commons/eip712.go
  internal/dataavailability/avail.go
  internal/dataavailability/celestia.go
  internal/nonodo/nonodo.go
  internal/rollup/fetcher.go
  internal/sequencers/avail/avail_client.go
  internal/sequencers/avail/avail_listener.go
  internal/sequencers/avail/config/config.go
  internal/sequencers/espresso/espresso_client.go
  main.go
Labels: avail

#216 Update CI with dotenv for Mac
  .github/workflows/ci.yaml
Labels: bug

#217 Resolve dotenv
  .github/workflows/ci.yaml
  main.go
  npm-package/src/nonodo.js
Labels: bug

#212 Pin version with bundle Anvil instead system
  .github/workflows/ci.yaml
  README.md
  go.mod
  internal/commons/handle_release.go
  internal/commons/utils.go
  internal/devnet/anvil.go
  main.go
  npm-package/src/nonodo.js
Labels: bug

#224 Ignore espresso test
  internal/sequencers/espresso/espresso_listener_test.go
Labels: espresso

#225 Revert fields from schema
  api/reader.graphql
  internal/reader/graph/generated.go
  internal/reader/reader.resolvers.go
  internal/sequencers/espresso/espresso_listener_test.go
  loadtesting/test.js
Labels: espresso

#219 Add diagram for Avail
  docs/avail.md
Labels: documentation

#223 Remove sqlite on memory except tests
  internal/nonodo/nonodo.go
Labels: enhancement

#222 Fix loop and change on goroutine and context
  .github/workflows/ci.yaml
  README.md
  go.mod
  internal/commons/handle_release.go
  internal/commons/utils.go
  internal/devnet/anvil.go
  internal/nonodo/nonodo.go
  internal/paio/paio.go
  internal/rollup/rollup.go
  internal/sequencers/avail/avail_client.go
  internal/sequencers/avail/avail_client_test.go
  internal/sequencers/avail/avail_listener.go
  internal/sequencers/avail/custom_client_avail.go
  internal/sequencers/avail/extrinsics/extrinsics.go
  internal/sequencers/inputter/inputter.go
  main.go
  npm-package/src/nonodo.js
Labels: bug, avail
