Repository Calindra/nonodo, pull requests merged in 2024-07, with the labels that each got.

#74 feat: celestia as DA
  .vscode/settings.json
  docs/celestia.md
  go.mod
  go.sum
  internal/contracts/celestia_relay.go
  internal/contracts/generate/main.go
  internal/dataavailability/celestia.go
  internal/dataavailability/celestia_commits.go
  internal/dataavailability/celestia_test.go
  internal/dataavailability/contracts/BlobstreamX.sol/BlobstreamX.go
  internal/dataavailability/contracts/ShareLoader.sol/ShareLoader.go
  internal/dataavailability/convert.go
  internal/rollup/fetcher.go
  main.go
  shell.nix
Labels: enhancement

#121 refactor: remove retry
  internal/nonodo/nonodo.go
  internal/sequencers/inputter/inputter.go
Labels: enhancement

#129 Feature/report sync
  DEV2DEV.md
  internal/convenience/container.go
  internal/convenience/decoder/decoder.go
  internal/convenience/decoder/decoder_test.go
  internal/convenience/model/type.go
  internal/convenience/repository/report_repository.go
  internal/convenience/repository/report_repository_test.go
  internal/convenience/repository/synchronizer_repository.go
  internal/convenience/services/service.go
  internal/convenience/synchronizer/graphile_fetcher.go
  internal/convenience/synchronizer/graphile_fetcher_test.go
  internal/convenience/synchronizer/graphile_synchornizer.go
  internal/convenience/voucher_exec_listener_test.go
  internal/model/model.go
  internal/model/model_test.go
  internal/model/state.go
  internal/nonodo/nonodo.go
  internal/reader/adapter.go
  internal/reader/adapter_test.go
  internal/reader/adapter_v1.go
  internal/reader/adapter_v2.go
  internal/reader/adapter_v2_test.go
  internal/reader/reader.resolvers.go
  internal/rollup/rollup_test.go
  main.go
Labels: HL GraphQL

#135 feat: report idempotency
  DEV2DEV.md
  internal/convenience/repository/report_repository.go
  internal/convenience/services/service.go
  internal/convenience/services/service_test.go
  internal/convenience/synchronizer/graphile_synchornizer.go
Labels: HL GraphQL

#134 Update rollups contract version to 2.0.0-rc.5 and devnet container image
  internal/contracts/application.go
  internal/contracts/generate/main.go
  internal/devnet/gen-devnet-state/main.go
Labels: enhancement

#138 Install anvil when dont found
  .dockerignore
  DEV2DEV.md
  Dockerfile
  Dockerfile.dev
  go.mod
  go.sum
  internal/commons/handle_release.go
  internal/commons/utils.go
  internal/devnet/anvil.go
  internal/devnet/anvil_test.go
  internal/nonodo/nonodo.go
  internal/supervisor/supervisor.go
  loadtesting/test.js
Labels: enhancement

#144 Fix some error with anvil in Windows
  .gitignore
  go.mod
  internal/commons/anvil.go
  internal/commons/anvil_window.go
  internal/commons/handle_release.go
  internal/devnet/anvil.go
  internal/nonodo/nonodo.go
Labels: bug

#149 108 reestablish connection to voucher execution listener
  DEV2DEV.md
  Dockerfile
  docker-compose.dev.yml
  internal/convenience/voucher_exec_listener.go
  internal/sequencers/inputter/inputter.go
  main.go
  postgraphile/Dockerfile.dev
  postgres/Dockerfile
Labels: enhancement
